name: Telegram Ping
on: workflow_dispatch

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping to Telegramaname: Telegram Ping
on: workflow_dispatch

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Show exact URLs (for debug)
        run: |
          echo "GET  https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/getMe"
          echo "POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage"

      - name: 1) getMe (token sanity check)
        run: |
          set -euxo pipefail
          curl -sS "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/getMe" | tee /tmp/getme.json
          echo "::notice::getMe response: $(cat /tmp/getme.json)"

      - name: 2) sendMessage (proper case!)
        run: |
          set -euxo pipefail
          curl -sS -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.CHAT_ID }}" \
            -d text="Ping from GitHub Actions ✅ $(date -u +'%Y-%m-%d %H:%M:%S UTC')" \
            -d disable_web_page_preview=true | tee /tmp/ping.json
          echo "::notice::sendMessage response: $(cat /tmp/ping.json)"

        run: |
          set -e
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.CHAT_ID }}" \
            -d text="Ping từ GitHub Actions ✅ $(date -u +'%Y-%m-%d %H:%M:%S UTC')" \
            -d disable_web_page_preview=true | tee /tmp/ping.json
          echo "::notice::Telegram API response: $(cat /tmp/ping.json)"
