name: Telegram Ping
on: workflow_dispatch

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping to Telegram
        run: |
          set -e
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.CHAT_ID }}" \
            -d text="Ping từ GitHub Actions ✅ $(date -u +'%Y-%m-%d %H:%M:%S UTC')" \
            -d disable_web_page_preview=true | tee /tmp/ping.json
          echo "::notice::Telegram API response: $(cat /tmp/ping.json)"
